#!/bin/bash
echo "Fake sonar-scanner"

#Check proper configuration of sonar
if [ "x$(grep 'eg.' .sonarc)" != "x" ]
then
    echo "Sonar has not been properly configured. Edit file '.sonarc'"
fi    

exit 1
